version: '3'

services:
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    container_name: notificationist-mysql
    environment:
      MYSQL_DATABASE: notificationist
      MYSQL_PASSWORD: development
      MYSQL_ROOT_PASSWORD: development
      MYSQL_USER: web
    image: mysql:8
    ports:
      - 3306:3306

  php:
    container_name: notificationist-php
    image: php:7.3-fpm
    volumes:
      - .:/development

  web:
    container_name: notificationist-web
    depends_on:
      - php
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/development
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
